import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { MainContainer } from "@/shared/ui";

const euclid = localFont({
  src: [
    {
      path: "../../public/fonts/euclid-circular-a/Euclid Circular A Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/euclid-circular-a/Euclid Circular A Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/euclid-circular-a/Euclid Circular A Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-euclid",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${euclid.variable} antialiased`}>
        <MainContainer>{children}</MainContainer>
      </body>
    </html>
  );
}
